### ISSUE TITLE
Busqueda tira error 500

### ISSUE THREAD

**Issue by martinvol** [martinvol/tallerII#56]

**Comment by martinvol** [comment]
Esto seguramente esté rompiendo los profesionales más populares, que la app también muestra "Todavía no implementado/error"

```
urlBusqueda: http://192.168.1.109:8000/search?size=10&pageNumber=1
12-03 01:09:05.215 20985-20985/ar.fiuba.jobify W/System.err: com.android.volley.NoConnectionError: java.net.ConnectException: Connection refused
12-03 01:09:05.218 20985-20985/ar.fiuba.jobify W/System.err:     at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:151)
12-03 01:09:05.219 20985-20985/ar.fiuba.jobify W/System.err:     at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:112)

```
Al parecer la busqueda está totalmente muerta

**Comment by MartinCura** [comment]
Aparentemente arreglado.
